### ISSUE TITLE
Fix nodegit auth problems

### ISSUE THREAD

**Issue by ryyppy** [flowtype/flow-typed#226] opened 2016-08-03 11:38 UTC
As discussed in #142, there seem to be several problems with `nodegit` not cloning the `flow-typed` repo because of authentication errors. Maybe there is a way to set some kind of `https://` cloning in `nodegit`?

Also there seem to be bugs of `nodegit` not setting a remote `master` for the cloned repo, which causes the `pull origin master` to fail. Maybe that's a side-effect of the unsuccessful clone tho.

(EDIT: we are using a `https://` url anyways: https://github.com/flowtype/flow-typed/blob/master/cli/src/lib/libDefs.js#L27)

**Comment by rexk** [comment] 2016-08-16 00:19
Hey @ryyppy, I also ran into the problem. As a work around, I manually cloned the repo into the cache directory, then changed the repo's protocol to use `http` instead of `https` and then my problem was solved.

```sh
[core]
       	repositoryformatversion = 0
       	filemode = true
       	bare = false
       	logallrefupdates = true
       	ignorecase = true
       	precomposeunicode = true
[remote "origin"]
       	url = http://github.com/flowtype/flow-typed.git
       	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
       	remote = origin
       	merge = refs/heads/master
```

I believe the problem is related to the following ticket: https://github.com/nodegit/nodegit/issues/330 which is closed about 2 years ago, but seems like the problem is revived.

**Comment by ryyppy** [comment] 2016-08-16 06:53
@rexk Yeah, this is exactly what I did,... I would like to know how many people experience this issue... so far there weren't to many complaints about cloning problems.

**Comment by jeffmo** [comment] 2016-09-07 20:41
Ok, just committed https://github.com/flowtype/flow-typed/pull/293 which changes the code to use http by default. I'll publish beta.7 now and we can see how it goes

**Comment by jeffmo** [comment] 2016-09-07 21:10
Ping @rexk/@rricard/@tunerex since you had original repros:

I'm curious what happens if you delete `~/.flow-typed` and run `flow-typed update-cache` with the new `beta.7` version?

**Comment by rexk** [comment] 2016-09-07 22:38
@jeffmo 
Thank you for the update. 😃 The update seems to be working.
Following commands did not give me single error or warning.

```sh
npm install -g flow-typed@2.0.0-beta.7
rm -rf ~/.flow-typed
flow-typed update-cache
```

PS: rexk and tunerex is my account. no need to ping double. 😄

**Comment by jeffmo** [comment] 2016-09-07 22:43
woo! Ok, I'll close this now and we can see if any more reports come in post-`beta.7`.

**Closed by jeffmo** 2016-09-07 22:43 UTC
Labels: bug, launch-blocking
