### ISSUE TITLE
Q: Is there a way to place libdef with library in one repo, not definitions hub?

### ISSUE THREAD

**Issue by burdiuz** [flowtype/flow-typed#1414] opened 2017-10-28 08:47 UTC
Hi!

Sorry, I may overlook it, but cannot find answer to this question. 
I am looking for a way to add libdef to my library projects, into 
same repo so they will be automatically grabbed by flow-typed 
when this library added to other projects, is it possible?
As I understood, I could add libdefs manually using [libs] section 
of .flowconfig file, but would be really nice if its done automatically.

**Comment by cprodescu** [comment] 2017-11-06 00:26
Besides interface libraries (similar to the ones distributed via `flow-typed`), `flow` will also try to read types from `node_modules`. Assuming `package.json['main']` is `dist/index.js`, flow will try to extract types from `dist/index.js.flow`, then from `dist/index.js`.

Distributing types directly with the libraries is the long term goal to strive for, unfortunately right now there isn't any support for distributing types for multiple versions of flow. As such, if you distribute any `React` components, you'll need to chose between flow `<0.53.0` or `>=0.53.0` compatibility.

Indeed documentation on this is not great, here is a discussion on it: https://github.com/facebook/flow/issues/1996#issuecomment-230919868

**Comment by cprodescu** [comment] 2017-11-06 00:54
Duplicate of #1451

**Comment by burdiuz** [comment] 2017-11-06 12:57
@cprodescu Thanks for answer, `index.js.flow` exactly what I was looking for!

**Closed** 2017-11-06 12:57 UTC
Labels: question

**Comment by Mouvedia** [comment] 2019-01-26 03:53
@burdiuz which IDE–plugin combination are you using?

**Comment by burdiuz** [comment] 2019-01-26 20:52
@Mouvedia I'm using VS Code but back then decided to not go with the flow in my projects so will not be able to assist you in any flow <> IDE questions, sorry.
