### ISSUE TITLE
I just can't get flow-typed to fail test

### ISSUE THREAD

**Issue by Gozala** [flowtype/flow-typed#1724] opened 2018-01-11 22:07 UTC
No mater what I write in my test file even if it's just `hello there` I still get this:

```
flow-typed run-tests
Running definition tests in /Users/gozala/Projects/flow-typed/definitions/npm...

Fetching all Flow binaries...

All tests passed!
```

**Comment by Gozala** [comment] 2018-01-11 22:45
Oddly enough I also can't get `./travis.sh` to succeed on my machine here is the output I get:

```
yarn install v1.1.0
warning You are using Node "9.3.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.64s.
yarn run v1.1.0
warning You are using Node "9.3.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
$ eslint **/**/test_*

/Users/gozala/Projects/flow-typed/definitions/npm/backbone-collection_v1.x.x/test_backbone-collection_v1.x.x.js
   5:14  warning  Unexpected use of weak type "any"       flowtype/no-weak-types
   8:14  warning  Unexpected use of weak type "any"       flowtype/no-weak-types
  11:22  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  30:29  warning  Unexpected use of weak type "any"       flowtype/no-weak-types
  33:23  warning  Unexpected use of weak type "any"       flowtype/no-weak-types
  35:17  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  36:16  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/backbone-model_v1.x.x/test_backbone-model_v1.x.x.js
   6:14  warning  Unexpected use of weak type "any"       flowtype/no-weak-types
   9:14  warning  Unexpected use of weak type "any"       flowtype/no-weak-types
  12:22  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  36:52  warning  Unexpected use of weak type "Object"    flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/backbone_v1.x.x/test_backbone-v1.x.x.js
  13:14  warning  Unexpected use of weak type "any"       flowtype/no-weak-types
  15:14  warning  Unexpected use of weak type "any"       flowtype/no-weak-types
  17:22  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  47:29  warning  Unexpected use of weak type "any"       flowtype/no-weak-types
  50:23  warning  Unexpected use of weak type "any"       flowtype/no-weak-types
  52:17  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  53:16  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/blacklist_v1.x.x/test_blacklist_v1.x.x.js
  4:33  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  5:37  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/bunyan_v1.x.x/test_bunyan_v1.x.x.js
  17:20  warning  Unexpected use of weak type "any"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/camelcase-keys_v3.x.x/test_camelcase-keys_v3.x.x.js
  3:15  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/commander_v2.x.x/test_commander_v2.x.x.js
  37:30  warning  Unexpected use of weak type "any"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/deepmerge_v1.x.x/test_deepmerge_v1.x.x.js
   7:16  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  31:37  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  31:48  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/express_v4.16.x/test_express_v4.16.x.js
  84:23  warning  Unexpected use of weak type "any"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/express_v4.x.x/test_express_v4.x.x.js
  69:23  warning  Unexpected use of weak type "any"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/fuzzaldrin_v2.x.x/test_fuzzaldrin_v2.js
  6:10  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/idb-keyval_v2.x.x/test_idb-keyval-v2.x.x.js
  16:44  warning  Unexpected use of weak type "any"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/idb_v2.x.x/test_idb-v2.x.x.js
  30:37  warning  Unexpected use of weak type "any"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/inline-style-prefixer_v3.x.x/test_inline-style-prefixer_v3.x.x.js
  5:15  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/inquirer_v2.x.x/test_rx_observable_array_v2.x.x.js
  41:17  warning  Unexpected use of weak type "any"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/inquirer_v2.x.x/test_rx_observable_create_v2.x.x.js
  9:9  warning  Unexpected use of weak type "any"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/isomorphic-fetch_v2.x.x/test_isomorphic-fetch_v2.js
  7:25  warning  Unexpected use of weak type "any"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/klasa_v0.3.x/test_klasa_v0.3.js
  17:22  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  19:18  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  49:24  warning  Unexpected use of weak type "any"     flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/koa-bunyan-logger_v2.x.x/test_koa_bunyan_logger_v2.x.x.js
  19:20  warning  Unexpected use of weak type "any"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/map-obj_v1.x.x/test_map-obj_v1.x.x.js
  3:18  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  3:79  warning  Unexpected use of weak type "any"     flowtype/no-weak-types
  3:92  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/mocha_v2.4.x/test_mocha_v2.4.x_hooks.js
   8:16  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  19:20  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  31:15  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  42:19  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/mocha_v2.4.x/test_mocha_v2.4.x_it.js
   8:20  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  26:25  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  46:25  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/mocha_v3.1.x/test_mocha_v3.1.x_hooks.js
   8:16  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  19:20  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  31:15  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  42:19  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/mocha_v3.1.x/test_mocha_v3.1.x_it.js
   9:20  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  25:25  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  43:25  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/mocha_v4.x.x/test_mocha_v4.x.x_hooks.js
   8:16  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  19:20  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  31:15  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  42:19  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/mocha_v4.x.x/test_mocha_v4.x.x_it.js
   9:20  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  25:25  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  43:25  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/morgan_v1.x.x/test_morgan.js
  29:58  warning  Unexpected use of weak type "any"  flowtype/no-weak-types
  29:68  warning  Unexpected use of weak type "any"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/normalizr_v2.x.x/test_normalizr-v2.js
  4:40  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  5:42  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  8:25  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/object-assign_v4.x.x/test_object-assign_v4.x.x.js
  5:16  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  6:16  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/papaparse_v4.x.x/test_papaparse_v4.x.x.js
  28:17  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  31:25  warning  Unexpected use of weak type "any"     flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/pify_v3.x.x/test_pify_v3.x.x.js
  3:20  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/primus_v5.x.x/test_primus-v5.js
  9:63  warning  Unexpected use of weak type "any"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/primus_v6.x.x/test_primus-v6.js
  9:63  warning  Unexpected use of weak type "any"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/prismic.io_v3.x.x/test_prismic.io_v3.x.x.js
   44:37  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
   49:44  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
   53:44  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
   55:72  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
   56:59  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
   71:27  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
   74:43  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  103:29  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  140:35  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  148:43  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  157:37  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  164:28  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  165:34  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  166:45  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  302:29  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/quill-delta_v3.5.x/test_quill-delta_v3.5.x.js
    7:21  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
   10:16  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
   97:15  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  105:15  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  113:38  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  127:37  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  133:37  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/react-i18next_v6.x.x/test_react-i18next_v6.x.x.js
  101:37  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/react-jss_v7.x.x/test_react-jss_v7.x.x.js
  161:12  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/react-select_v1.x.x/test_react-select_v1.x.x.js
   7:31  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  10:31  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  11:30  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  12:33  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  13:32  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  19:32  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  20:31  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  63:21  warning  Unexpected use of weak type "any"     flowtype/no-weak-types
  67:26  warning  Unexpected use of weak type "any"     flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/redux-devtools-extension_v2.x.x/test_redux-devtools-extension_v2.x.x.js
  69:21  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  70:26  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/redux-form_v5.x.x/test_redux-form_v5.js
  19:25  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  20:20  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  21:21  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
  33:32  warning  Unexpected use of weak type "any"       flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/redux-saga-thunk_v0.5.x/test_redux-saga-thunk_v0.5.x.js
  10:43  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/rxjs_v5.0.x/test_rxjs.js
   92:34  warning  Unexpected use of weak type "any"  flowtype/no-weak-types
  103:19  warning  Unexpected use of weak type "any"  flowtype/no-weak-types
  217:56  warning  Unexpected use of weak type "any"  flowtype/no-weak-types
  218:52  warning  Unexpected use of weak type "any"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/sinon_v2.x.x/test_sinon_v2.x.x.js
    4:19  warning  Unexpected use of weak type "Function"  flowtype/no-weak-types
    6:20  warning  Unexpected use of weak type "any"       flowtype/no-weak-types
   57:22  warning  Unexpected use of weak type "any"       flowtype/no-weak-types
   58:18  warning  Unexpected use of weak type "any"       flowtype/no-weak-types
  166:16  warning  Unexpected use of weak type "any"       flowtype/no-weak-types
  175:16  warning  Unexpected use of weak type "any"       flowtype/no-weak-types
  185:16  warning  Unexpected use of weak type "any"       flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/twit_v2.x.x/test_twit_v2.x.x.js
  16:30  warning  Unexpected use of weak type "any"  flowtype/no-weak-types
  17:29  warning  Unexpected use of weak type "any"  flowtype/no-weak-types

/Users/gozala/Projects/flow-typed/definitions/npm/underscore_v1.x.x/test_underscore-v1.js
  171:20  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types
  172:13  warning  Unexpected use of weak type "Object"  flowtype/no-weak-types

✖ 130 problems (0 errors, 130 warnings)

✨  Done in 9.34s.
yarn install v1.1.0
warning You are using Node "9.3.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
$ mkdirp dist && npm run test

> flow-typed@2.2.3 test /Users/gozala/Projects/flow-typed/cli
> npm run clean && npm run build && npm run test-quick


> flow-typed@2.2.3 clean /Users/gozala/Projects/flow-typed/cli
> rimraf dist


> flow-typed@2.2.3 build /Users/gozala/Projects/flow-typed/cli
> mkdirp dist && babel ./src --out-dir=./dist

src/cli.js -> dist/cli.js
src/commands/__tests__/install-test.js -> dist/commands/__tests__/install-test.js
src/commands/__tests__/runTests-test.js -> dist/commands/__tests__/runTests-test.js
src/commands/__tests__/search-test.js -> dist/commands/__tests__/search-test.js
src/commands/create-stub.js -> dist/commands/create-stub.js
src/commands/install.js -> dist/commands/install.js
src/commands/runTests.js -> dist/commands/runTests.js
src/commands/search.js -> dist/commands/search.js
src/commands/update-cache.js -> dist/commands/update-cache.js
src/commands/update.js -> dist/commands/update.js
src/commands/validateDefs.js -> dist/commands/validateDefs.js
src/commands/version.js -> dist/commands/version.js
src/lib/TEST_UTILS.js -> dist/lib/TEST_UTILS.js
src/lib/__mocks__/node.js -> dist/lib/__mocks__/node.js
src/lib/__tests__/cacheRepoUtils-test.js -> dist/lib/__tests__/cacheRepoUtils-test.js
src/lib/__tests__/codeSign-test.js -> dist/lib/__tests__/codeSign-test.js
src/lib/__tests__/flowVersion-test.js -> dist/lib/__tests__/flowVersion-test.js
src/lib/__tests__/libDefs-test.js -> dist/lib/__tests__/libDefs-test.js
src/lib/__tests__/semver-test.js -> dist/lib/__tests__/semver-test.js
src/lib/cacheRepoUtils.js -> dist/lib/cacheRepoUtils.js
src/lib/codeSign.js -> dist/lib/codeSign.js
src/lib/fileUtils.js -> dist/lib/fileUtils.js
src/lib/flowProjectUtils.js -> dist/lib/flowProjectUtils.js
src/lib/flowVersion.js -> dist/lib/flowVersion.js
src/lib/git.js -> dist/lib/git.js
src/lib/github.js -> dist/lib/github.js
src/lib/isInFlowTypedRepo.js -> dist/lib/isInFlowTypedRepo.js
src/lib/libDefs.js -> dist/lib/libDefs.js
src/lib/node.js -> dist/lib/node.js
src/lib/npm/__tests__/npmLibDefs-test.js -> dist/lib/npm/__tests__/npmLibDefs-test.js
src/lib/npm/npmLibDefs.js -> dist/lib/npm/npmLibDefs.js
src/lib/npm/npmProjectUtils.js -> dist/lib/npm/npmProjectUtils.js
src/lib/semver.js -> dist/lib/semver.js
src/lib/stubUtils.js -> dist/lib/stubUtils.js
src/lib/validationErrors.js -> dist/lib/validationErrors.js

> flow-typed@2.2.3 test-quick /Users/gozala/Projects/flow-typed/cli
> jest && npm run lint

 PASS  src/lib/npm/__tests__/npmLibDefs-test.js
  ● Console

    console.log src/lib/cacheRepoUtils.js:128
      • rebasing flow-typed cache...

 PASS  src/commands/__tests__/install-test.js
 PASS  src/lib/__tests__/cacheRepoUtils-test.js
 PASS  src/lib/__tests__/libDefs-test.js
 PASS  src/commands/__tests__/search-test.js
 PASS  src/lib/__tests__/flowVersion-test.js
 PASS  src/lib/__tests__/codeSign-test.js
 PASS  src/lib/__tests__/semver-test.js
 FAIL  src/commands/__tests__/runTests-test.js (7.238s)
  ● run-tests (command) › regression 1385 › returns error code if $ExpectError tes
t doesn't fail

    expect(received).toEqual(expected)

    Expected value to equal:
      1
    Received:
      0

      at _callee2$ (src/commands/__tests__/runTests-test.js:23:30)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:64:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:355:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:116:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:64:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:154:20)
      at node_modules/regenerator-runtime/runtime.js:201:11
          at new Promise (<anonymous>)
      at callInvokeWithMethodAndArg (node_modules/regenerator-runtime/runtime.js:200:16)
      at AsyncIterator.enqueue [as _invoke] (node_modules/regenerator-runtime/runtime.js:223:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:116:21)
      at Object.<anonymous>.runtime.async (node_modules/regenerator-runtime/runtime.js:244:14)
      at Object._callee2 (src/commands/__tests__/runTests-test.js:22:111)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>

  ● run-tests (command) › regression 1385 › console logs about unused suppression

    expect(collection)[.not].toContainEqual(value)

    Expected collection to be an array-like structure.
    Received: undefined

      at _callee3$ (src/commands/__tests__/runTests-test.js:32:36)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:64:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:355:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:116:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:64:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:154:20)
      at node_modules/regenerator-runtime/runtime.js:201:11
          at new Promise (<anonymous>)
      at callInvokeWithMethodAndArg (node_modules/regenerator-runtime/runtime.js:200:16)
      at AsyncIterator.enqueue [as _invoke] (node_modules/regenerator-runtime/runtime.js:223:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:116:21)
      at Object.<anonymous>.runtime.async (node_modules/regenerator-runtime/runtime.js:244:14)
      at Object._callee3 (src/commands/__tests__/runTests-test.js:26:135)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>

Test Suites: 1 failed, 8 passed, 9 total
Tests:       2 failed, 96 passed, 98 total
Snapshots:   0 total
Time:        9.859s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flow-typed@2.2.3 test-quick: `jest && npm run lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flow-typed@2.2.3 test-quick script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gozala/.npm/_logs/2018-01-11T22_43_45_200Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flow-typed@2.2.3 test: `npm run clean && npm run build && npm run test-quick`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flow-typed@2.2.3 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gozala/.npm/_logs/2018-01-11T22_43_45_291Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by Gozala** [comment] 2018-01-11 23:43
I'm not sure what is wrong with my setup but I just can't get past this errors, I installed same version of node as in travis and removed global flow but still having same errors

**Comment by dolma** [comment] 2018-01-12 02:49
Got the exact same issue as you, tried everything I could think of but no solution in sight.
Would love to know if anyone else has had the same problem and found a working solution.

**Comment by Gozala** [comment] 2018-01-12 04:29
@dolma One thing I noticed in the discussion on #1725 that on my machine it actually seem to run any tests, as it appears on travis https://travis-ci.org/flowtype/flow-typed/jobs/327897772#L923 when tests are running files being tested and flow versions are printed out, which does not happen on my machine, which leads me to believe `flow-typed` is unable to find test files

**Comment by Gozala** [comment] 2018-01-12 04:37
@GAntoine are you running on linux by a chance ? I wonder if something isn't quite working on OSX.

**Comment by GAntoine** [comment] 2018-01-12 04:46
Nope, running it on High Sierra. What version of flow-typed are you using?

**Comment by dolma** [comment] 2018-01-12 04:55
@Gozala Yes same thing as you, when I run it on my machine it just gives the same exact 2 errors as you have, which don't seem to be related to any test at all. Then the same code, when tested on travis after I committed it, shows versions being tested and actual flow error descriptions.
Running High Sierra Version 10.13.1 (17B1003) and flow-typed version 2.2.3

**Comment by GAntoine** [comment] 2018-01-12 15:24
Then yeah, my last recommendation would be to blow everything away, re-clone the repo and re-install `flow-typed`. With such similar setups, and me being able to run it no problem, that's probably your best best (but I can't give any promises).

**Comment by saadq** [comment] 2018-01-14 13:24
FWIW, I am also running into this same issue, even when I use a fresh clone of the project. Here is a full [terminal log](https://gist.github.com/saadq/04ff1d06960f2cbb004e2ae48c1d056b) of what happens.

After running all the commands, I seem to always get this result when running tests (regardless of the input):

```
Running definition tests against latest 15 flow versions in /Users/squadri/Projects/flow-typed/definitions/npm...

Fetching all Flow binaries...
 
All tests passed!
```

---

Steps to reproduce:

1. Clone this repo
2. `cd` into the cloned repo
3. Run the following commands:

```
cd definitions
yarn install
yarn test
cd ../cli
yarn
node dist/cli.js validate-defs ../definitions
node dist/cli.js run-tests
```

---

**OS**: macOS Sierra Version 10.12.6
**flow-typed**: v2.2.3
**Node**: v8.3.0

**Comment by KenanY** [comment] 2018-01-23 14:58
Can someone try this patch?

```patch
diff --git a/cli/src/commands/runTests.js b/cli/src/commands/runTests.js
index 72645eb..82636a5 100644
--- a/cli/src/commands/runTests.js
+++ b/cli/src/commands/runTests.js
@@ -149,7 +149,9 @@ async function getOrderedFlowBinVersions(
           // Find the binary zip in the list of assets
           const binZip = rel.assets
             .filter(({name}) => {
-              return OS_ARCH_FILTER_RE.test(name) && !/-latest.zip$/.test(name);
+              return OS_ARCH_FILTER_RE.test(name)
+                && !/-latest.zip$/.test(name)
+                && /^flow-/.test(name);
             })
             .map(asset => asset.browser_download_url);
```

Recent flow releases now have an additional asset: `libflowparser-ARCH-VERSION.zip`. The most recent release, v0.64.0, **only has a linux64** release. So, on systems with that arch, [this condition](https://github.com/flowtype/flow-typed/blob/e36161f044496df4da9d7022fa86b996bac2b123/cli/src/commands/runTests.js#L156) will fail because now two assets remain after the filtering, instead of the expected one. The CLI then silent throws an error, hence why no other versions get downloaded. The above patch ensures that `libflowparser` is filtered out from the list of binaries.

**Comment by saadq** [comment] 2018-01-23 22:09
Hmm, I still seem to have the same issue. Here is what I did, let me know if I missed something:

**1.** I cloned the repo.

**2.** I changed `flow-typed/cli/src/commands/runTests.js` from this:

```js
const binZip = rel.assets
  .filter(({name}) => {
    return OS_ARCH_FILTER_RE.test(name) && !/-latest.zip$/.test(name);
  })
  .map(asset => asset.browser_download_url);
```

to this:


```js
const binZip = rel.assets
  .filter(({name}) => {
    return OS_ARCH_FILTER_RE.test(name)
      && !/-latest.zip$/.test(name)
      && /^flow-/.test(name);
  })
  .map(asset => asset.browser_download_url);
```

**3.** I ran the following commands:

```bash
cd definitions
yarn install
yarn test
cd ../cli
yarn
node dist/cli.js validate-defs ../definitions
node dist/cli.js run-tests asdfasdf
```

Terminal Output: [Gist](https://gist.github.com/anonymous/2f6623cebd3aca5027e0df8ff5bea90b).
Git Diff: [Gist](https://gist.github.com/anonymous/4c48a3c9fb0438d8611ba0b188dc436d).

Here's a screenshot of the diff:

![screen shot 2018-01-23 at 5 05 37 pm](https://user-images.githubusercontent.com/5678694/35303400-cf9143e4-005f-11e8-9bdd-4b7073a21e74.png)

Let me know if I can provide any other info.

**Comment by KenanY** [comment] 2018-01-23 22:31
@saadq Can you try running `npm run build` from within `cli/` after applying the patch? Then try `run-tests` again.

**Comment by saadq** [comment] 2018-01-23 23:32
Same result unfortunately. 

Output: https://gist.github.com/anonymous/15f6b16001b24bc27084c03ecb2834c0

**Comment by KenanY** [comment] 2018-01-24 01:27
@saadq Oh, I just noticed you're on a Mac. What I suspect is happening in your case is that [the latest flow release](https://github.com/facebook/flow/releases/tag/v0.64.0) does not have a `flow-osx-VERSION.zip` asset like previous versions do. This is almost certainly causing [the same conditional](https://github.com/flowtype/flow-typed/blob/e36161f044496df4da9d7022fa86b996bac2b123/cli/src/commands/runTests.js#L156) I mentioned above to pass, since the result of the asset filtering will just be an empty array. Possible solutions would be to skip `flow@0.64.0` on Mac, or more generally: skip releases which don't have a built binary for the user's system.

**Comment by saadq** [comment] 2018-01-24 09:42
Ah, I see – good catch. Do you think an issue should be opened in the main `flow` repo about a missing binary for macOS?

**Comment by KenanY** [comment] 2018-01-24 13:59
Perhaps. I wonder if it's because [the Travis build](https://travis-ci.org/facebook/flow/builds/332267188) is still going after >24 hours 🤔

**Comment by GAntoine** [comment] 2018-01-24 15:26
There's an open issue at https://github.com/facebook/flow/issues/5709

**Closed** 2018-01-27 19:43 UTC
Labels: question

**Comment by saadq** [comment] 2018-01-27 20:10
Thanks very much for the quick fix! :)

**Comment by GAntoine** [comment] 2018-01-27 22:27
@saadq I'm just hoping its the right fix! I'll release a patch soon, and you can let me know if it's been fixed.
