### ISSUE TITLE
Flow runs infinitely consuming all memory on my mac

### ISSUE THREAD

**Issue by pronebird** [flowtype/flow-typed#643] opened 2017-02-03 18:24 UTC
Hi,

I have this funny problem with flow, it seems it goes into some sort of recursion forcing `kernel_task` to consume over 10GB of RAM and creating 50GB swap. At this point my mac goes pretty crazy and asks me to kill some apps.

`sudo fs_usage` reveals that flow reads from disk continuously.

After half an hour my mac turns into jet making funny noise like I am playing AAA video game, but I am just editing javascripts.

I am not sure if that's the problem with flow or VS plugin. Disabling plugin resolved the problem.

<img width="777" alt="screenshot 2017-02-01 10 34 50" src="https://cloud.githubusercontent.com/assets/704044/22503606/6bc44d10-e86a-11e6-859c-512783187cdc.png">

<img width="885" alt="screenshot 2017-02-01 10 29 59" src="https://cloud.githubusercontent.com/assets/704044/22503435/a82c4e16-e869-11e6-9b41-35d5b432ed82.png">

**Comment by pasih** [comment] 2017-04-18 19:55
This happens to me as well and I'm using Atom.

![screen shot 2017-04-18 at 22 46 52](https://cloud.githubusercontent.com/assets/3005740/25150054/50ea14ba-2489-11e7-8c35-a16f49e57c12.png)

Here's code that I managed to reproduce this twice with (I included the entire repo in case it's a combination of whatever other tools are involved):

https://github.com/pasih/flow-api-example/blob/kills-flow/src/index.js
(Nevermind the broken code.. trying to puzzle out how to do something and not doing great yet). 

"Flow, a static type checker for JavaScript, version 0.43.1",
Atom 1.16.0 x64
MacOS Sierra, 10.12.4. Macbook Pro, 13-inch mid 2014, 8gb.

If you need any extra information, let me know.

**Comment by SteveMellross** [comment] 2017-05-06 13:10
Might want to post this on the flow repo:

https://github.com/facebook/flow/issues/2152

**Comment by gaastonsr** [comment] 2017-05-11 18:30
Happened to me when I forgot to ignore node_modules in my flowconfig

**Comment by GAntoine** [comment] 2017-10-11 22:48
Closing since this is most likely an issue with flow, and there's an open issue on the flow repo.

**Closed by GAntoine** 2017-10-11 22:48 UTC
Labels: cli-bug
