### ISSUE TITLE
[CLI] install command fails in CircleCI

### ISSUE THREAD

**Issue by shinout** [flowtype/flow-typed#247] opened 2016-08-11 18:08 UTC
In CircleCI,
```sh
flow-typed install -f 0.30 redux
```

The command fails with the following message.

```text
flow-typed cache not found, fetching from GitHub...ERROR: Unable to clone the local cache repo.
UNCAUGHT ERROR: Error: Malformed URL 'ssh://git@github.com:/flowtype/flow-typed.git'
    at Error (native)
```

**Comment by thejameskyle** [comment] 2016-08-12 01:26
Duplicate of #226

**Closed by thejameskyle** 2016-08-12 01:26 UTC
