### ISSUE TITLE
react-redux mapStateToProps problem

### ISSUE THREAD

**Issue by hmeerlo** [flowtype/flow-typed#436] opened 2016-11-05 09:33 UTC
Hi,

don't know if this is the right place to ask, but I'll try anyway. Is it wrong for me to expect that flow would not report a problem in the code below? It complains on the line accessing this.props.b about 'b' property not being found. I would expect that because of the mapStateToProps flow would know that the b property from the state is accessible in the props. Or am I doing something wrong?

Regards,
Herman

```
// @flow
import React, {PropTypes} from 'react'; // eslint-disable-line no-unused-vars
import {connect} from 'react-redux';

type TMyState = {
  b: number
}

type Props = {
  a: number;
}

class TestCase extends React.Component<void, Props, void> {
  render(){
    let ret = this.props.b;
    return(
      <div>{ret}</div>
    );
  }
}

function mapStateToProps(state: TMyState) {
  return {
    b: state.b
  }
}

export default connect(mapStateToProps)(TestCase);
```

**Comment by relekang** [comment] 2016-11-05 10:11
I think that it behaves as expected as the type for props is defined. Given that [this example][] also gives the same error the issue is not with the definitions of react-redux but rather with flow, if it is an error at all.

[this example]: https://flowtype.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMY4A0oA3gApazoAqAnuoQM4C+okDqoAORYS5QQG5QIUJ2jIAdjgC0AE2QdiAI2iElc+YVDzYSgK7zTHQiqUA3Ylg6JEONofqMOoALw1EoUGIALiNTVE1CLHFELmdSaGIOLyZOHABhRMNCAA8cQnkVLyIyHAA6NNgMWANFAB5bWGQVKg90DioGpoA+PwCRAsiACgBKan8A0B08ETxfHAALdVL0BjbSzWiJ0BnTLHlB8a3atVsu6hmuWuATrsPQYc3QWNjESHNyZGrQJlAR3u3CDhdvJQLUUhx0plAt5qABGHiaGEAJh4wC60S4QA

**Comment by AgentME** [comment] 2016-12-05 02:58
I'm having this problem too.

**Comment by AgentME** [comment] 2016-12-14 23:40
I just solved the same type of problem in react-dnd's definitions in this commit: https://github.com/flowtype/flow-typed/pull/543/commits/f28e378737bfc2ff64b80bf6a9955a31a9d84be2. I may look into this in a few days.

**Comment by hmeerlo** [comment] 2017-03-16 15:11
@AgentME Did you pursue this in any way? I find myself Googling for this issue about once a month and then I end up at my own question every time (it's even worse, I just made a testcase for the problem which resembles the testcase above for about 98% :-) ). The current flowtype definitions for react-redux seem to imply that this should somehow work and I'm wondering whether there is anyone who has successfully used it?

**Comment by hmeerlo** [comment] 2017-05-02 13:33
Ah back again at my own question more than a year later :-) Nope not solved yet, it seems like Facebook isn't really into redux and Flow in their own codebase.

**Comment by 0x24a537r9** [comment] 2017-08-18 18:10
Our team (at Oculus, so Facebook) uses Flow and Redux, although Flow is not yet rich enough to support your use case automatically. That said, the workaround that we use is incredibly easy and very typesafe. A simplified example from our codebase for how we handle it:

```
import React from 'react';
import {connect} from 'react-redux';

import type {State as DeeplinkingState} from 'HomeDeeplinkingReducer';
import type {
  ReduxProps,  // Our type alias for dispatch() and other props attached by connect()
  State as StoreState,
} from 'HomePrimeStore';

type ReduxMappedProps = {
  deeplinking: DeeplinkingState,
};
type OwnProps = {
  error: ?Error,
};
type Props = ReduxMappedProps & ReduxProps & OwnProps;

const HomeDeeplinkCompletionMarker = (props: Props) => {
  ...
};

function mapStateToProps(
  state: StoreState,
  ownProps: OwnProps,
): ReduxMappedProps {
  return {
    deeplinking: state.deeplinking,
  };
}

export default connect(mapStateToProps)(HomeDeeplinkCompletionMarker);
```

Hope that helps!

**Comment by charlesoconor** [comment] 2017-09-18 16:54
That's too bad there is too so much boilerplate. It would be really nice if it could infer the prototypes that come out of `connect`. All of those types already exists in `StoreState` so it shouldn't be too bad. 

I'm stuck behind flow [v0.41 ](https://github.com/facebook/flow/blob/master/Changelog.md#v0410)mostly because of this issue.

**Comment by lukeapage** [comment] 2018-03-17 19:32
this appears fixed in the latest typings for react-redux. Meaning you don't appear to need to specify anything and it just infers.

**Comment by macrozone** [comment] 2018-03-18 21:02
@lukeapage that looks awesome. in which version is this fixed?

**Comment by lukeapage** [comment] 2018-03-19 05:17
The v5 typings that went in recently.
2 things so far: errors are only detected on usage of the component, no support for map state to props returning a function

**Comment by AndrewSouthpaw** [comment] 2018-04-04 05:58
I think this is addressed, closing for now, feel free to speak up if that's not the case.

**Closed by AndrewSouthpaw** 2018-04-04 05:58 UTC
Labels: libdef, question
