### ISSUE TITLE
* flow-typed cache not found, fetching from GitHub...ERROR: Unable to clone the local cache repo.

### ISSUE THREAD

**Issue by MoOx** [flowtype/flow-typed#142] opened 2016-06-14 09:17 UTC
I am not able to `install` at type definition. Not sure what is wrong with github (my internet access is ok and github is up - proof is this issue).

```
$ npm install -g flow-typed
/Users/MoOx/.nvm/versions/node/v5.11.0/bin/flow-typed -> /Users/MoOx/.nvm/versions/node/v5.11.0/lib/node_modules/flow-typed/dist/cli.js

> nodegit@0.13.2 install /Users/MoOx/.nvm/versions/node/v5.11.0/lib/node_modules/flow-typed/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Completed installation successfully.

> nodegit@0.13.2 postinstall /Users/MoOx/.nvm/versions/node/v5.11.0/lib/node_modules/flow-typed/node_modules/nodegit
> node postinstall.js

/Users/MoOx/.nvm/versions/node/v5.11.0/lib
└─┬ flow-typed@2.0.0-beta.5 
  ├─┬ babel-polyfill@6.9.1 
  │ ├── babel-runtime@6.9.2 
  │ ├── core-js@2.4.0 
  │ └── regenerator-runtime@0.9.5 
  ├─┬ github@0.2.4 
  │ └── mime@1.3.4 
  ├── lodash@4.13.1 
  ├─┬ md5@2.1.0 
  │ ├── charenc@0.0.1 
  │ ├── crypt@0.0.1 
  │ └── is-buffer@1.1.3 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  ├─┬ nodegit@0.13.2 
  │ ├─┬ fs-extra@0.26.7 
  │ │ ├── graceful-fs@4.1.4 
  │ │ ├── jsonfile@2.3.1 
  │ │ ├── klaw@1.3.0 
  │ │ ├── path-is-absolute@1.0.0 
  │ │ └─┬ rimraf@2.5.2 
  │ │   └─┬ glob@7.0.3 
  │ │     ├── inflight@1.0.5 
  │ │     └─┬ minimatch@3.0.0 
  │ │       └─┬ brace-expansion@1.1.4 
  │ │         ├── balanced-match@0.4.1 
  │ │         └── concat-map@0.0.1 
  │ ├─┬ node-pre-gyp@0.6.28 
  │ │ ├─┬ nopt@3.0.6 
  │ │ │ └── abbrev@1.0.7 
  │ │ ├─┬ npmlog@2.0.4 
  │ │ │ ├── ansi@0.3.1 
  │ │ │ ├─┬ are-we-there-yet@1.1.2 
  │ │ │ │ ├── delegates@1.0.0 
  │ │ │ │ └─┬ readable-stream@2.1.4 
  │ │ │ │   └── buffer-shims@1.0.0 
  │ │ │ └─┬ gauge@1.2.7 
  │ │ │   ├── has-unicode@2.0.0 
  │ │ │   ├─┬ lodash.pad@4.4.0 
  │ │ │   │ ├── lodash._baseslice@4.0.0 
  │ │ │   │ ├── lodash._basetostring@4.12.0 
  │ │ │   │ └── lodash.tostring@4.1.3 
  │ │ │   ├── lodash.padend@4.5.0 
  │ │ │   └── lodash.padstart@4.5.0 
  │ │ ├─┬ rc@1.1.6 
  │ │ │ ├── deep-extend@0.4.1 
  │ │ │ ├── ini@1.3.4 
  │ │ │ ├── minimist@1.2.0 
  │ │ │ └── strip-json-comments@1.0.4 
  │ │ ├─┬ tar@2.2.1 
  │ │ │ ├── block-stream@0.0.9 
  │ │ │ ├── fstream@1.0.9 
  │ │ │ └── inherits@2.0.1 
  │ │ └─┬ tar-pack@3.1.3 
  │ │   ├─┬ debug@2.2.0 
  │ │   │ └── ms@0.7.1 
  │ │   ├── fstream-ignore@1.0.5 
  │ │   ├─┬ once@1.3.3 
  │ │   │ └── wrappy@1.0.2 
  │ │   ├── readable-stream@2.0.6 
  │ │   └── uid-number@0.0.6 
  │ └─┬ promisify-node@0.3.0 
  │   └─┬ nodegit-promise@4.0.0 
  │     └── asap@2.0.4 
  ├─┬ request@2.72.0 
  │ ├── aws-sign2@0.6.0 
  │ ├── aws4@1.4.1 
  │ ├─┬ bl@1.1.2 
  │ │ └─┬ readable-stream@2.0.6 
  │ │   ├── core-util-is@1.0.2 
  │ │   ├── isarray@1.0.0 
  │ │   ├── process-nextick-args@1.0.7 
  │ │   ├── string_decoder@0.10.31 
  │ │   └── util-deprecate@1.0.2 
  │ ├── caseless@0.11.0 
  │ ├─┬ combined-stream@1.0.5 
  │ │ └── delayed-stream@1.0.0 
  │ ├── extend@3.0.0 
  │ ├── forever-agent@0.6.1 
  │ ├─┬ form-data@1.0.0-rc4 
  │ │ └── async@1.5.2 
  │ ├─┬ har-validator@2.0.6 
  │ │ ├─┬ commander@2.9.0 
  │ │ │ └── graceful-readlink@1.0.1 
  │ │ ├─┬ is-my-json-valid@2.13.1 
  │ │ │ ├── generate-function@2.0.0 
  │ │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ │ └── is-property@1.0.2 
  │ │ │ ├── jsonpointer@2.0.0 
  │ │ │ └── xtend@4.0.1 
  │ │ └─┬ pinkie-promise@2.0.1 
  │ │   └── pinkie@2.0.4 
  │ ├─┬ hawk@3.1.3 
  │ │ ├── boom@2.10.1 
  │ │ ├── cryptiles@2.0.5 
  │ │ ├── hoek@2.16.3 
  │ │ └── sntp@1.0.9 
  │ ├─┬ http-signature@1.1.1 
  │ │ ├── assert-plus@0.2.0 
  │ │ ├─┬ jsprim@1.2.2 
  │ │ │ ├── extsprintf@1.0.2 
  │ │ │ ├── json-schema@0.2.2 
  │ │ │ └── verror@1.3.6 
  │ │ └─┬ sshpk@1.8.3 
  │ │   ├── asn1@0.2.3 
  │ │   ├── assert-plus@1.0.0 
  │ │   ├─┬ dashdash@1.14.0 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── ecc-jsbn@0.1.1 
  │ │   ├─┬ getpass@0.1.6 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── jodid25519@1.0.2 
  │ │   ├── jsbn@0.1.0 
  │ │   └── tweetnacl@0.13.3 
  │ ├── is-typedarray@1.0.0 
  │ ├── isstream@0.1.2 
  │ ├── json-stringify-safe@5.0.1 
  │ ├─┬ mime-types@2.1.11 
  │ │ └── mime-db@1.23.0 
  │ ├── node-uuid@1.4.7 
  │ ├── oauth-sign@0.8.2 
  │ ├── qs@6.1.0 
  │ ├── stringstream@0.0.5 
  │ ├── tough-cookie@2.2.2 
  │ └── tunnel-agent@0.4.3 
  ├── rx-lite@4.0.8 
  ├── semver@5.1.0 
  ├─┬ table@3.7.8 
  │ ├── bluebird@3.4.0 
  │ ├─┬ chalk@1.1.3 
  │ │ ├── ansi-styles@2.2.1 
  │ │ ├── escape-string-regexp@1.0.5 
  │ │ ├── has-ansi@2.0.0 
  │ │ └── supports-color@2.0.0 
  │ ├── slice-ansi@0.0.4 
  │ ├─┬ string-width@1.0.1 
  │ │ ├─┬ code-point-at@1.0.0 
  │ │ │ └── number-is-nan@1.0.0 
  │ │ └── is-fullwidth-code-point@1.0.0 
  │ ├─┬ strip-ansi@3.0.1 
  │ │ └── ansi-regex@2.0.0 
  │ ├── tv4@1.2.7 
  │ └── xregexp@3.1.1 
  ├── through@2.3.8 
  └─┬ yargs@4.7.1 
    ├── camelcase@3.0.0 
    ├─┬ cliui@3.2.0 
    │ └── wrap-ansi@2.0.0 
    ├── decamelize@1.2.0 
    ├─┬ lodash.assign@4.0.9 
    │ ├── lodash.keys@4.0.7 
    │ └── lodash.rest@4.0.3 
    ├─┬ os-locale@1.4.0 
    │ └─┬ lcid@1.0.0 
    │   └── invert-kv@1.0.0 
    ├─┬ pkg-conf@1.1.3 
    │ ├─┬ find-up@1.1.2 
    │ │ └── path-exists@2.1.0 
    │ ├─┬ load-json-file@1.1.0 
    │ │ ├─┬ parse-json@2.2.0 
    │ │ │ └─┬ error-ex@1.3.0 
    │ │ │   └── is-arrayish@0.2.1 
    │ │ ├── pify@2.3.0 
    │ │ └─┬ strip-bom@2.0.0 
    │ │   └── is-utf8@0.2.1 
    │ ├── object-assign@4.1.0 
    │ └── symbol@0.2.3 
    ├─┬ read-pkg-up@1.0.1 
    │ └─┬ read-pkg@1.1.0 
    │   ├─┬ normalize-package-data@2.3.5 
    │   │ ├── hosted-git-info@2.1.5 
    │   │ ├─┬ is-builtin-module@1.0.0 
    │   │ │ └── builtin-modules@1.1.1 
    │   │ └─┬ validate-npm-package-license@3.0.1 
    │   │   ├─┬ spdx-correct@1.0.2 
    │   │   │ └── spdx-license-ids@1.2.1 
    │   │   └─┬ spdx-expression-parse@1.0.2 
    │   │     └── spdx-exceptions@1.0.4 
    │   └── path-type@1.1.0 
    ├── require-main-filename@1.0.1 
    ├── set-blocking@1.0.0 
    ├── window-size@0.2.0 
    ├── y18n@3.2.1 
    └─┬ yargs-parser@2.4.0 
      └── camelcase@2.1.1 


~/myproject master* 1m 49s
❯ flow-typed install -f 0.27 redux@3.0.0
 * flow-typed cache not found, fetching from GitHub...ERROR: Unable to clone the local cache repo.
UNCAUGHT ERROR: Error: authentication required but no callback set
    at Error (native)
```

**Comment by ryyppy** [comment] 2016-06-14 09:25
Hmm, not sure if this subcommand is already in npm, but try the following:

```
flow-typed update-cache --debug
```

Maybe we get more information about the error then... I guess it's a git-config problem with github and not a direct problem with flow-typed itself...

**Comment by tunerex** [comment] 2016-06-29 21:18
+1. Having same problem here.

**Comment by ryyppy** [comment] 2016-06-30 09:54
There is apparently some problem (at least usability wise), I will try to find some time on the weekend to look into that.

**Comment by ryyppy** [comment] 2016-07-06 10:53
@MoOx Do you still have the problem? If so, the newest version on NPM includes the `update-cache` command I mentioned a while ago... could you run it and post the output? :-)

**Comment by MoOx** [comment] 2016-07-06 13:26
Seems ok now. But wowww. 16min to install !

```
❯ npm install -g flow-typed

> nodegit@0.15.1 preinstall /Users/MoOx/.nvm/versions/node/v5.11.0/lib/node_modules/.staging/nodegit-4f29389c
> node lifecycleScripts/preinstall

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
/Users/MoOx/.nvm/versions/node/v5.11.0/bin/flow-typed -> /Users/MoOx/.nvm/versions/node/v5.11.0/lib/node_modules/flow-typed/dist/cli.js

> nodegit@0.15.1 install /Users/MoOx/.nvm/versions/node/v5.11.0/lib/node_modules/flow-typed/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Running install script
[nodegit] Success: "/Users/MoOx/.nvm/versions/node/v5.11.0/lib/node_modules/flow-typed/node_modules/nodegit/build/Release/nodegit.node" is installed via remote
[nodegit] Completed installation successfully.

> nodegit@0.15.1 postinstall /Users/MoOx/.nvm/versions/node/v5.11.0/lib/node_modules/flow-typed/node_modules/nodegit
> node lifecycleScripts/postinstall

- ansi@0.3.1 node_modules/flow-typed/node_modules/ansi
- lodash._baseslice@4.0.0 node_modules/flow-typed/node_modules/lodash._baseslice
- lodash._basetostring@4.12.0 node_modules/flow-typed/node_modules/lodash._basetostring
- lodash.tostring@4.1.3 node_modules/flow-typed/node_modules/lodash.tostring
- lodash.padstart@4.5.0 node_modules/flow-typed/node_modules/lodash.padstart
- lodash.padend@4.5.0 node_modules/flow-typed/node_modules/lodash.padend
- lodash.pad@4.4.0 node_modules/flow-typed/node_modules/lodash.pad
- node-pre-gyp@0.6.28 node_modules/flow-typed/node_modules/nodegit/node_modules/node-pre-gyp
- readable-stream@2.0.6 node_modules/flow-typed/node_modules/tar-pack/node_modules/readable-stream
/Users/MoOx/.nvm/versions/node/v5.11.0/lib
└─┬ flow-typed@2.0.0-beta.6 
  ├─┬ nodegit@0.15.1 
  │ ├─┬ fs-extra@0.26.7
  │ │ └── rimraf@2.5.3 
  │ ├── nan@2.3.5 
  │ ├─┬ node-gyp@3.4.0 
  │ │ ├── fstream@1.0.10 
  │ │ ├─┬ glob@7.0.5 
  │ │ │ └── fs.realpath@1.0.0 
  │ │ ├─┬ minimatch@3.0.2 
  │ │ │ └── brace-expansion@1.1.5 
  │ │ ├─┬ nopt@3.0.6
  │ │ │ └── abbrev@1.0.9 
  │ │ ├─┬ npmlog@3.1.2 
  │ │ │ ├── console-control-strings@1.1.0 
  │ │ │ ├─┬ gauge@2.6.0 
  │ │ │ │ ├── aproba@1.0.4 
  │ │ │ │ ├── has-color@0.1.7 
  │ │ │ │ ├── has-unicode@2.0.1 
  │ │ │ │ ├── signal-exit@3.0.0 
  │ │ │ │ └── wide-align@1.1.0 
  │ │ │ └── set-blocking@2.0.0 
  │ │ ├─┬ osenv@0.1.3 
  │ │ │ ├── os-homedir@1.0.1 
  │ │ │ └── os-tmpdir@1.0.1 
  │ │ ├─┬ path-array@1.0.1 
  │ │ │ └─┬ array-index@1.0.0 
  │ │ │   └─┬ es6-symbol@3.1.0 
  │ │ │     ├── d@0.1.1 
  │ │ │     └─┬ es5-ext@0.10.12 
  │ │ │       └── es6-iterator@2.0.0 
  │ │ └─┬ which@1.2.10 
  │ │   └── isexe@1.1.2 
  │ └─┬ node-pre-gyp@0.6.29 
  │   └── tar-pack@3.1.4 
  ├─┬ request@2.72.0
  │ └─┬ http-signature@1.1.1
  │   └── jsprim@1.3.0 
  ├── semver@5.2.0 
  ├─┬ table@3.7.8
  │ └── bluebird@3.4.1 
  └─┬ yargs@4.7.1
    └── set-blocking@1.0.0 


~/Sync/Development master* 16m 3s
```

**Comment by jeffmo** [comment] 2016-07-06 13:33
Ugh, yea npm install is so slow :(

Would you mind opening an issue for install speed? (I'm on my phone and afraid I'll forget before I get back to my computer). I noticed this the other day and I think it's something we should dig into

**Comment by jeffmo** [comment] 2016-07-07 01:24
Oh, haha -- I'd already filed an issue for this :p https://github.com/flowtype/flow-typed/issues/107

**Comment by jeffmo** [comment] 2016-07-08 02:32
Ok, so sounds like the OP issue is resolved with the latest release

**Closed by jeffmo** 2016-07-08 02:32 UTC

**Comment by tunerex** [comment] 2016-07-08 18:01
Still having same issue on Node@6.2.2, NPM@3.9.5, and flow-typed@2.0.0-beta.6

```sh
flow-typed update-cache --debug
Updating flow-typed definitions...
 * flow-typed cache not found, fetching from GitHub...ERROR: Unable to clone the local cache repo.
Update failed: authentication required but no callback set
Error: authentication required but no callback set
    at Error (native)
```

**Comment by ryyppy** [comment] 2016-07-08 18:40
I am 62% sure that you might not have configured your github cli / registered a public ssh key for your github account... did you do that?

**Comment by rricard** [comment] 2016-07-25 18:48
@ryyppy - the issue is sometimes we may want to run flow-typed in an environment where the git cli is not configured (CI for instance).

**Comment by ryyppy** [comment] 2016-07-28 12:04
@rricard I think you would be better off, if you would track your flow-typed folder in your git project, after you installed it. In that way, nobody using the project is actually reliant on the `flow-typed` cli tool.

At least, that is what we are doing in our production code right now ;-)

**Comment by rricard** [comment] 2016-07-28 12:32
@ryyppy: I have found a workaround and I agree with that _but_ I think it's worth reopening the issue to at least track it. You clearly state in the README that feedback on the cli is welcome: this is some feedback 😉

**Comment by ryyppy** [comment] 2016-07-28 14:10
I am totally with you! Maybe it would be a good idea to create a new issue, which will ask for HTTPS support, which doesn't require a configured SSH-Key configuration? I think this would solve many problems in the future. Not sure if the used library supports this? @jeffmo

**Comment by thejameskyle** [comment] 2016-08-02 19:20
Can everything just fall back to downloading a zip file from GitHub? Just to keep things working 100% of the time?

**Comment by jeffmo** [comment] 2016-08-02 20:07
I didn't realize github requires auth to simply clone a repo, but if so it would be good to understand if there's a way around this. If not, then some kind of periodic zipped release seems like a good fallback.

We should look into the auth thing and see if we can find the root of the issue, though. Adding machinery to deal with non-git-repos for updating could get hairy since this system is fairly broadly based around the notion of github/history/PRs/etc.

**Comment by ryyppy** [comment] 2016-08-03 11:33
@jeffmo we always had problems when we had a `package.json` pointing to a `git+ssh://` reference... all our devs without a properly configured github keychain got auth error messages. As soon as we switched to the `https://` clone urls everything worked. 

I recently got errors as well when I tried to get my cache downloaded and I actually had to go into the `~/.flow-typed/repo` directory and manually configure the remote `master` (which apparently was unknown?) ... `node-git` seem to make some troubles in various ways.

**Comment by mithuns** [comment] 2019-01-14 20:42
Still does not work  and I just checked I have ssh setup on my windows device.

```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         2/4/2018  11:53 PM           1675 id_rsa
-a----         2/4/2018  11:53 PM            420 id_rsa.pub
-a----         7/6/2018  10:36 AM           3326 id_rsa1
-a----         7/6/2018  10:36 AM            747 id_rsa1.pub
-a----       11/13/2017  11:57 AM            792 known_hosts
```

This just hangs for hours

```
PS C:\Users\mithuns\git\electron-react-boilerplate> flow-typed update-cache --debug
Updating flow-typed definitions...
• flow-typed cache not found, fetching from GitHub...

```

Whats the solution for this ? Sorry, if I am a bit late to this thread. seems like there was a identified solution for this.
