### ISSUE TITLE
Error: flow_v0.38.x <=v0.52.x: Unexpected trailing characters:  <=v0.52.x

### ISSUE THREAD

**Issue by etrepum** [flowtype/flow-typed#1151] opened 2017-08-17 20:54 UTC
We started getting this error when running `flow-typed update` today:

```
$ yarn run flow-typed update
yarn run v0.27.5
$ "/app/node_modules/.bin/flow-typed" "update"
• Found 93 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...


UNCAUGHT ERROR: Error: flow_v0.38.x <=v0.52.x: Unexpected trailing characters:  <=v0.52.x
    at validationError (/app/node_modules/flow-typed/dist/lib/validationErrors.js:14:11)
    at parseDirString (/app/node_modules/flow-typed/dist/lib/flowVersion.js:155:45)
    at _callee2$ (/app/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:543:146)
    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:116:21)
    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:64:40)
    at invoke (/app/node_modules/regenerator-runtime/runtime.js:154:20)
    at /app/node_modules/regenerator-runtime/runtime.js:164:13
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I guess it's related to these:

```
$ git grep '<=v' .
react-redux_v5.x.x.js:// flow-typed version: 19506e57e6/react-redux_v5.x.x/flow_>=v0.30.x <=v0.52.x
react-router-dom_v4.x.x.js:// flow-typed version: 19506e57e6/react-router-dom_v4.x.x/flow_>=v0.38.x <=v0.52.x
react-router_v4.x.x.js:// flow-typed version: 19506e57e6/react-router_v4.x.x/flow_>=v0.30.x <=v0.52.x
```

Currently we have a CI script that tries to sync our repo with flow-typed, which is where this error surfaced first:

```bash
#!/bin/bash -e

FLOW_CACHE=$HOME/.flow-typed
FLOW_REPO=$FLOW_CACHE/repo
FLOW_CACHE_BEFORE_UPDATE=$(cat $FLOW_CACHE/last-update || true)
yarn run flow-typed update-cache
FLOW_CACHE_AFTER_UPDATE=$(cd $FLOW_REPO && git rev-parse HEAD)

if [[ "$FLOW_CACHE_BEFORE_UPDATE" != "$FLOW_CACHE_AFTER_UPDATE" ]]; then
  echo "flow-typed cache updated, running flow-typed update."

  yarn run flow-typed update
  git add flow-typed
  if [[ -n "$(git diff-index --name-only HEAD)" ]]; then
    echo "flow-typed updated definitions, committing."
    git commit -am "Update flow-typed definitions"
  else
    echo "flow-typed did not update definitions, skipping"
  fi
else
  echo "flow-typed cache didn't update, skipping"
fi

echo $FLOW_CACHE_AFTER_UPDATE > $FLOW_CACHE/last-update
```

**Comment by grundmanise** [comment] 2017-08-19 10:58
I've got the same problem, have you found a solution?

**Comment by etrepum** [comment] 2017-08-19 19:02
No. We just stopped using the tool in CI altogether. The definitions are checked in, so we figured this would be fixed before we really had to worry about it.

**Comment by zabute** [comment] 2017-08-21 09:59
```rm -rf flow-typed && flow-typed update``` works for me

**Comment by aihkas** [comment] 2017-08-21 14:17
same problem here, it appeared after upgrading flow 0.5.3, while "rm -rf flow-typed" solved the probelm there seems to be some inconsistency.

**Comment by oriSomething** [comment] 2017-08-22 07:34
For me `rm -rf flow-typed ~/.flow-typed` or any one of them alone didn't work :(

**Comment by klaasn** [comment] 2017-08-22 07:41
I had to do this and also remove flow-typed (npm -g remove flow-typed && npm -g install flow-typed) to get things working again.

**Comment by oriSomething** [comment] 2017-08-22 07:47
I've also tried this. Didn't work. I've also tried to downgrade, didn't work. I suspect one or more of the dependencies causes this. But, I really have no idea.
Moreover, since the CI always uses fresh copy, I quite suck.

**Comment by oriSomething** [comment] 2017-08-22 07:56
**Update:**
It seems to trigger from `flow-typed install jest@20`. Not sure why, it used to work until recently

**Comment by Baptiste-Garcin** [comment] 2017-08-22 08:33
Same here, pretty sure it's one of the dependencies...
And also : I meet the bug while `flow-typed install`. And only when some libdef are already present in the flow-typed file

**Comment by jazmon** [comment] 2017-08-23 08:24
This happened for me after upgrading to `flow-bin@0.53` and running `flow-typed update`. 

Some definition files were modified to include the breaking part `<=v0.52.x`, for example in **react-router-dom** `// flow-typed version: 19506e57e6/react-router-dom_v4.x.x/flow_>=v0.38.x <=v0.52.x`. 

This issue started after I had to roll back to `flow-bin@0.52` and now **flow-typed** started to throw this error.

Issue was fixed by search and removing each `<=v0.52.x` from the flow-typed folder.

**Comment by ivanicharts** [comment] 2017-08-25 08:05
For me issue was fixed by removing trailing space in react-redux_v5.x.x.js on second line, here:
 `"v0.30.x <=v0.52.x":`

The line:
`// flow-typed version: aff2bf770e/react-redux_v5.x.x/flow_>=v0.30.x <=v0.52.x`

**Comment by lydell** [comment] 2017-09-05 16:48
Here is how to reproduce the bug 100%: https://github.com/lydell/flow-typed-bug

**Comment by FezVrasta** [comment] 2017-09-08 17:05
Can we get this bug fixed? It's really invalidating...

**Comment by JerryGreen** [comment] 2017-10-03 09:09
lold, this unnecessary space...
this is so confusing
I have spent 2+ hours on this

**Closed** 2017-10-05 19:46 UTC
